// BUILT IN MODULES 
// OPERTING SYSTEM
// FILE SYSTEM
// HTTP SERVER 
// PATH

// HTTP



// NPM
// PACKAGE.JSON 
// TO SWET UP MY PACKAGE.JSON I NEED TO RUN npm init or npm init -y
// NPM INSTALLS PACKAGES INTO NODE MODULES MEANING  NPM CREATES node_modules 

